spring:
  application:
    name: linkforge
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

app:
  cache:
    ttl: ${CACHE_TTL:24h}
  shortener:
    strategy: ${SHORTENER_STRATEGY:sequential} # Options: sequential, random
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:linkforge}
    username: ${DB_USER:linkforge_user}
    password: ${DB_PASSWORD:linkforge_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: ${SHOW_SQL:true}
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: ${SERVER_PORT:8080}


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.linkforge: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: ${SHOW_SQL:DEBUG}
